[book]
authors = ["jk"]
language = "en"
multilingual = false
src = "src"
title = ""

[output.html]
additional-css = ["theme/css/additional.css",]
additional-js = []
default-theme = "dark"
preferred-dark-them = "ayu"
no-selection-label = true
site-url = "/"
cname = ""

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 0